### ISSUE TITLE
Diagram 的 sequence/flow 颜色过淡

### ISSUE THREAD

**Issue by PYGC** [FishionYu/typora-blubook-theme#17]
~~~markdown
```sequence
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
```

```flow
st=>start: Start
op=>operation: Your Operation
cond=>condition: Yes or No?
e=>end

st->op->cond
cond(yes)->e
cond(no)->op
```
~~~

发现和 css 里 `.md-fences, tt` 的 `color` 有关

~~~css
.md-fences, tt {
  border-radius: 3px;
  color: #f0f0f0;
  padding: 0;
  font-size: 0.9em;
}
~~~

**Comment by PYGC** [comment]
如图所示
![微信截图_20201009151419](https://user-images.githubusercontent.com/16513529/95554073-27fddd00-0a42-11eb-9c37-62a5d3eadb1e.png)
![微信截图_20201009151431](https://user-images.githubusercontent.com/16513529/95554089-2af8cd80-0a42-11eb-9181-ac3794b0d065.png)

**Comment by PYGC** [comment]
```css
.md-fences, tt {
  color: #183055;
}

.md-fences .code-tooltip {
  background-color:#F0F0F0;
}
```
