### ISSUE TITLE
目录出现scroll bar的时候颜色是否可以调统一啊？

### ISSUE THREAD

**Issue by siriusmax** [FishionYu/typora-blubook-theme#35]
如果左边目录很多需要scroll bar的时候，颜色主题好像不是很统一。不过很棒的主题，感谢分享！

![image](https://user-images.githubusercontent.com/23714883/103301320-21db2500-49cf-11eb-8c2d-d0f48c8dbbe6.png)

**Comment by Higurashi-kagome** [comment]
感谢使用和反馈，目前为止我没有遇到该问题（在 Windows 上测试），请问能否提供详细的复现步骤？

<details>
<summary>可供参考的模板</summary>

1. 打开某某某......
2. 点击某某某......
3. 滚动到某某某......
4. 问题出现

</details>

**Comment by siriusmax** [comment]
感谢你的回复。typora和主题都是最新的版本，不过我的是MacOS BigSur的环境。 复现的话，我其实没有什么特别的操作，大概尝试了这样会出现该问题：缩小窗口，直到左侧目录栏无法容纳所有条目, 这时候垂直的scroll bar会出现，颜色不统一。如果文件名过长则会导致水平的scroll bar出现，颜色同样不统一。不知道这样是否有帮助。

**Comment by Higurashi-kagome** [comment]
很有帮助，但很可惜我不方便在 macOs 上测试，所以你能否提供帮助？ @siriusmax 

具体步骤是：

1. 在 Typora 设置页中打开主题文件夹
2. 在主题文件夹的 blubook.css 文件末尾添加：

	  <details>
	  <summary>Code</summary>
	  
	  ```CSS
		    /*** scroll bar ***/
		    #typora-sidebar::-webkit-scrollbar {
		      width: 8px !important;
		      height: 8px !important;
		      background-color: rgba(0,0,0,0) !important;
		      position: absolute !important;
		    }
		    #typora-sidebar::-webkit-scrollbar-corner {
		      background: 0 0 !important;
		    }
		    #typora-sidebar::-webkit-scrollbar-thumb {
		      background: rgba(0,0,0,0.3) !important;
		      background-clip: padding-box !important;
		    }
	  ```
	  
	  </details>

3. 保存文件后重启 Typora 进行测试，查看问题是否仍然存在
