### ISSUE TITLE
两边白边太宽！

### ISSUE THREAD

**Issue by 838239178** [FishionYu/typora-blubook-theme#40]
我下的最新release，在我的typora上两边白边很宽，和图片不一样啊！很难受
![效果图](https://user-images.githubusercontent.com/55338151/106577956-f45b3b80-6579-11eb-9577-73604c13f4d1.jpg)

**Comment by Higurashi-kagome** [comment]
这是我的显示，似乎没那么宽：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/106579317-844db500-657b-11eb-8d8d-b9644818afd7.png)

</details>

是不是因为修改了字体大小？

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/106579418-a5aea100-657b-11eb-9681-d2324f3bd9bf.png)

</details>

**Comment by 838239178** [comment]
> 这是我的显示，似乎没那么宽：
> 
> Details
> ![image](https://user-images.githubusercontent.com/51501079/106579317-844db500-657b-11eb-8d8d-b9644818afd7.png)
> 
> 是不是因为修改了字体大小？
> 
> Details
> ![image](https://user-images.githubusercontent.com/51501079/106579418-a5aea100-657b-11eb-9681-d2324f3bd9bf.png)

字体大小是设置的`自动`

**Comment by Higurashi-kagome** [comment]
暂时不清楚原因，不过比较容易作修改：

```CSS
/****** #write basic ******/
#write {
  position: static;
  width: 90%;
  max-width: 700px;
  line-height: 1.6;
  transform: none;
  height: auto;
}
```

比如可以试着修改上述代码中的 `width` 及 `max-width` 属性。

**Comment by 838239178** [comment]
我自己debug改了css，把700改成1000就好多了，建议这个地方用百分比之类的吧
```css
#write{
    max-length: 1000px
}
```
