### ISSUE TITLE
大纲列表太紧凑，怎么改

### ISSUE THREAD

**Issue by 838239178** [FishionYu/typora-blubook-theme#41]
大纲列表太紧凑了，而且还搭配的粗体，不利于观看目录，如何更改
<details>
<summary>对比图</summary>

![1](https://user-images.githubusercontent.com/55338151/106708463-e109a800-662d-11eb-871b-c2af8975433e.jpg)

![2](https://user-images.githubusercontent.com/55338151/106708468-e23ad500-662d-11eb-95a0-b054f9852b44.jpg)

</details>

**Comment by Higurashi-kagome** [comment]
可以尝试修改 `.outline-item` 的 `padding-top` 和 `padding-bottom` 样式：

```CSS
.outline-item {
    padding-top: 6px;
    padding-bottom: 3px;
}
```
