### ISSUE TITLE
右边文本区

### ISSUE THREAD

**Issue by chenjiazhi1014** [FishionYu/typora-blubook-theme#49]
右边文本区要改个背景色怎么改？

**Comment by Higurashi-kagome** [comment]
可尝试使用 CSS 样式：

```CSS
/* write 为文本区 id */
#write{
	background-color: antiquewhite;
}
```

更多调试技巧可参考 [Write Custom Theme for Typora。](https://theme.typora.io/doc/Write-Custom-Theme/)
